apiVersion: v1
kind: PersistentVolume
metadata:
  name: todoapp-pv
  namespace: todoapp
spec:
  storageClassName: standard
  persistentVolumeReclaimPolicy: Retain
  accessModes: ["ReadWriteMany"]
  capacity: 
    storage: 1Gi
  hostPath: 
    path: /data/